### ISSUE TITLE
[Docker] Warehouse leaving zombies with exim4

### ISSUE THREAD

**Issue by PillowOfBricks** [Ravinou/borgwarehouse#101]
When I last logged into my server, I noticed 800+ zombie processes that are related to exim4. Recreating the container clears the processes, but I'd rather not crontab a graveyard sweep. The only form of notifications I have enabled is apprise to a Telegram channel.

**Comment by Ravinou** [comment]
Hi @PillowOfBricks , yep this the bug that cause #98 . I'm on it.

**Comment by Ravinou** [comment]
Fixed in latest 2.1.0
