### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by Gaming4LifeDE** [Ravinou/borgwarehouse#102]
Is borgwarehouse multi user capable? I've experimented with it a bit but haven't found a way to create multiple users. If it isn't, I think this should be on the agenda, despite it most likely being a lot of work to implement.

Maybe it would be a good idea to think about what's needed to implement this.

**Comment by dhenry123** [comment]
I think this is a very bad idea. In the current context the data is very well isolated. In addition, I've just provided to the team, one container that can start with an arbitrary UID. It's better to start several containers with their own volumes group, and thus have a very high privilege separation. 
You have 2 clients, not very complicated, 200? not more complicated using ansible...
This will avoid many security complications
+++

**Comment by xyhhx** [comment]
@Gaming4LifeDE As a workaround until/if ever multitenancy is supported, you can use forward auth alongside your SSO provider of choice to "fake" it

**Comment by Ravinou** [comment]
Hi, it's a long-term feature that will take a lot of time. I have a lot of new features and improvements to make first. I'm not saying it won't happen, but I don't know when it will :)

In the meantime, with docker support, the best solution for multi-user remains to use containers as @dhenry123 rightly said. It's even a better idea from a security and isolation point of view.

I'll close the subject for now. I'll reopen the issue when the time comes.
