### ISSUE TITLE
Docker install error reading Dockerfile

### ISSUE THREAD

**Issue by daydone** [Ravinou/borgwarehouse#111]
I am seeing errors when attempting to build the docker image
# docker build -t borgwarehouse .
[+] Building 0.0s (2/2) FINISHED                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 2B                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                   0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3178582253/Dockerfile: no such file or directory

**Comment by zionio** [comment]
If you are using windows maybe this could help you https://github.com/docker/for-win/issues/8781

**Comment by daydone** [comment]
@zionio Thank you, I am on Rocky Linux 9 so unfortunately no help here. Hopefully helps someone else!
