### ISSUE TITLE
Can I use it with borgbackup2 or only v1 ? 

### ISSUE THREAD

**Issue by bitcandy** [Ravinou/borgwarehouse#113]
Hello, 
Thank you for you time building borgwarehouse.
The question:
Can I use it with borgbackup2 or only v1 ? 
Thanks

**Comment by zionio** [comment]
Hi, 
I'm not the right person to answer you, but based on https://www.borgbackup.org/releases/borg-2.0.html "_Breaking compatibility_" I would say no atm.

**Comment by Ravinou** [comment]
Hi @bitcandy , support for borg 2.0 will be provided after release 2.0. For the moment, borg 2.0 is still in beta but obviously, work will be done to make borgwarehouse compatible once Borg v2 is stable 😀
