### ISSUE TITLE
Storage size says "Go" instead of "gb"

### ISSUE THREAD

**Issue by nadir-ishiguro** [Ravinou/borgwarehouse#126]
Pretty much just the title. I was a bit confused by that. I'd also put a space between the number and the unit.

Great tool by the way. Just gave it a go and it's very convenient.

**Comment by kylemanna** [comment]
Was confused by this as well.

**Comment by Ravinou** [comment]
Hi everyone 😀, and thank you for your interest about Borgwarehouse.

To get to the point, I think I even have to use GB (capitalized). Because these are bytes, not bits, so the naming convention seems to be `GB`. Is it okay if I fix this ? I'll also add a space.

**Comment by nadir-ishiguro** [comment]
Yes of course. You're right. Thank you!

**Comment by Ravinou** [comment]
Fixed ✌️
