### ISSUE TITLE
Kubernetes Pod: Bind to port 22. Permission denied

### ISSUE THREAD

**Issue by maxim-mityutko** [Ravinou/borgwarehouse#129]
Hello, I'm trying to run BorgWarehouse in Kubernetes, using the official image - `borgwarehouse/borgwarehouse:v2.1.0` 
The WebUI runs as expected, however I cannot connect to Borg via Vorta or Borgmatic.
In the client I'm getting the following error:
```
[Init Repo] ERROR: Connection closed by remote host. Is borg working on the server?
```
In the `sshd.log` of the BorgWarehouse I see that `sshd` could not bind to port 22:
```
2024-01-06T17:21:07.713852+00:00 sshd Bind to port 22 on 0.0.0.0 failed: Permission denied.
2024-01-06T17:21:07.713892+00:00 sshd Bind to port 22 on :: failed: Permission denied.
2024-01-06T17:21:07.713897+00:00 sshd Cannot bind any address.
```
I guess this is the reason why I can't connect from the borg client, but I have no idea why the sshd can't start properly.
Any ideas?

**Comment by maxim-mityutko** [comment]
I've edited the `sshd_config` file that was created after the first execution of the pod. And specified different port there.
This change persists between runs as the `ssh-host` is mounted to external folder. After the restart of the container, the `sshd` started correctly, and i'm able to connect to the server from the client.

**Comment by Ravinou** [comment]
Hi @maxim-mityutko maybe you can tweak the SSH option on line 10 on [supervisord file too](https://github.com/Ravinou/borgwarehouse/blob/main/docker/supervisord.conf). Adding `-p 30022` will work I think.

Can I close the issue ? Thanks for your interest in my software :)
