### ISSUE TITLE
Latest docker image doesn't start

### ISSUE THREAD

**Issue by Magneticdud** [Ravinou/borgwarehouse#130]
Starting the latest docker image gives this error:

```
Error: The directory named as part of the path /home/borgwarehouse/logs/supervisord.log does not exist
For help, use /usr/bin/supervisord -h
```

**Comment by pulsar895** [comment]
Hello,

@Magneticdud
I had the same problem. Check the volumes on this page, there have been changes that break the startup if you update.

@Ravinou
Is it possible to have a page indicating the changes on the container?

**Comment by Magneticdud** [comment]
oooh missed that change in the docker-compose.yml

thanks for the hint, once added the new tmp and logs volumes (with appropriate permissions) it worked fine

**Comment by Ravinou** [comment]
Hi, yep the changelog is with the release note here : https://github.com/Ravinou/borgwarehouse/releases/tag/v2.1.0

**Comment by Magneticdud** [comment]
If someone else has this problem (didn't notice the update because running the image with the `latest ` tag and like to live dangerously with automatic unattended updates), not only need to add the new two volumes, but also need to add the cronjobs to your servers (actually a good idea, as you can decide when and how)

The commands i added to the cronjob of the host is:

```
docker exec CONTAINERNAME curl --request POST --url 'http://CONTAINERNAME:3000/api/cronjob/checkStatus' --header 'Authorization: Bearer CRONJOB_KEY'
docker exec CONTAINERNAME curl --request POST --url 'http:/CONTAINERNAME:3000/api/cronjob/getStorageUsed' --header 'Authorization: Bearer CRONJOB_KEY'
```

(or use the env variable by specifying where's the .env to the exec command)

(note: i use docker exec to run the curl command inside the container as i don't expose port 3000, but it's routed via a proxy + password and it would be harder to do otherwise)

**Comment by Ravinou** [comment]
@Magneticdud Thank you so much for sponsoring ❤️. That give me the strength to continue working on this project on weekends and evenings. Readme of the project is updated with your name.
