### ISSUE TITLE
WebUI info about repo doesnt match borg statistics

### ISSUE THREAD

**Issue by c-yco** [Ravinou/borgwarehouse#131]
I did a fresh docker setup of borgwarehouse and created a repo in the ui. 
Then I pointed my existing borgmatic container against the container ( updated borgmatic configs) 
Backups from borgmatic run fine, I can see multiple successfull backups: 
<img width="649" alt="image" src="https://github.com/Ravinou/borgwarehouse/assets/355591/0ae5963a-ec38-4d36-aeca-4649afb7838a">

Also I can see the stats for the repo direclty from the borgwarehouse container using borg: 
<img width="628" alt="image" src="https://github.com/Ravinou/borgwarehouse/assets/355591/50a990c5-2c90-4561-a57e-ad549dfeadc8">

Still the webui shows the following: 

<img width="611" alt="image" src="https://github.com/Ravinou/borgwarehouse/assets/355591/b84884bc-dd5e-49f1-ba9b-3988f862384d">

Already tried a restart of the borgwarehouse container.

**Comment by c-yco** [comment]
Forget it, I did another read on the cron jobs. 
Perhaps some Info in the UI when the last status update was triggered and a button to trigger it manually would be nice

**Comment by Ravinou** [comment]
Hi @c-yco , the status of your repo is not up to date, nor is your volume. I think you simply haven't set up your scheduled tasks. [The doc is here](https://borgwarehouse.com/docs/admin-manual/docker-installation/#scheduled-tasks). Let me know if it's OK, thanks :)

**Comment by c-yco** [comment]
;)

**Comment by Ravinou** [comment]
A forced trigger button is a good idea. I'll implement it.
