### ISSUE TITLE
Feature: Add logging for api calls

### ISSUE THREAD

**Issue by c-yco** [Ravinou/borgwarehouse#134]
Currently the container is not logging very much, so its hard the debug if for example the cron jobs are not working. 
the borgwarehouse.log should contain log messages if the cron api was called. 

Current log after container start: 
` Getting SSH fingerprints...`

Expected log during startup:
```
Last status update call: 2024-01-08 ..
Last storage stats call:  2024-01-08 ..
...
```

And when one of the cron api points is called:
```
API call for status update

Update successfull
```

**Comment by Ravinou** [comment]
I've reworked some of the logs in v2.2.0 (see the release readme). However, I didn't find it useful to add a log for each storage/status update. Indeed, it's an event that happens every 5 minutes or less, which generates a huge amount of useless logging.

When you make the API call, I checked and you do have a log on the client side if the call fails.
