### ISSUE TITLE
Connection closed by remote host

### ISSUE THREAD

**Issue by RosaEinhorn** [Ravinou/borgwarehouse#145]
Hi,

thanks (again) for creating this awesome piece of software.
I am having an issue where the repository-server seems to close the SSH connection on very long tasks (the log is from a check that fails after ~5 hours):
```
Remote: client_loop: send disconnect: Broken pipe
RemoteRepository: 182 B bytes sent, 1.01 MB bytes received, 3 messages sent
Connection closed by remote host
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/borg/archiver.py", line 189, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borg/archiver.py", line 349, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space, max_duration=args.max_duration):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/local/lib/python3.11/site-packages/borg/remote.py", line 828, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host
```

Is it possible to configure SSH inside the docker container to make the connection more reliable?
Thanks a lot in advance.

**Comment by Ravinou** [comment]
Hi @RosaEinhorn !  Thank you for your thanks ❤️

Currently, you can tune SSH options directly in `docker/supervisord.conf`, line 10. But this is not very practical. So I'm planning to make the **sshd_config** configuration file available so that everyone can do what they want with it.

In the meantime, I think you can add `-o ClientAliveInterval=600 -o ClientAliveCountMax=0`

You can also maintain a client-side keepalive with SSH.

**Comment by RosaEinhorn** [comment]
Hi @Ravinou , thank your for your help and the hint.
I have changed the configuration as suggested. For everybody facing the same issue, you should noch edit the suggested file under ```/home/borgwarehouse/app/supervisord.conf``` directly as this file is part of the container and will be changed on the next restart.
You should mount the file (ro) inside docker-compose.yml, e.g.:
```
[...]
    volumes:
      - ${CONFIG_PATH:?CONFIG_PATH variable missing}:/home/borgwarehouse/app/config
      - ${SSH_PATH:?SSH_PATH variable missing}:/home/borgwarehouse/.ssh
      - ${SSH_HOST:?SSH_HOST variable missing}:/etc/ssh
      - ${BORG_REPOSITORY_PATH:?BORG_REPOSITORY_PATH variable missing}:/home/borgwarehouse/repos
      - ${TMP_PATH:?TMP_PATH variable missing}:/home/borgwarehouse/tmp
      - ${LOGS_PATH:?LOGS_PATH variable missing}:/home/borgwarehouse/logs
      - ./somefolder/supervisord.conf:/home/borgwarehouse/app/supervisord.conf:ro
 [...[
```

(Un)fortunately I cannot reproduce this easily as it only happens rarely (during a backup check), but I will monitor it and report back. I think we can close this for now. :)

**Comment by Ravinou** [comment]
Latest v2.2.0 provides a [default configuration file](https://borgwarehouse.com/docs/admin-manual/security/#sshd-default-configuration) for SSHD. The last two lines of the configuration take this into account. I therefore close it. Thanks
