### ISSUE TITLE
[Enhancement]: Add support to use the same key on multiple repos

### ISSUE THREAD

**Issue by zionio** [Ravinou/borgwarehouse#147]
Hi,
 currently borgwarehouse uses the same username `borgwarehouse` for all repositories created, so it is not possible to re-use the same public key for more than one repository because of a single `authorized_keys` file.

An interesting improvement could be to create a random username for each repository, exactly as the repository name, and assign the user their own `authorized_keys`.

Bye and thanks 👋

**Comment by Ravinou** [comment]
Hi @zionio, [BorgWarehouse v1](https://v1.borgwarehouse.com/) worked like this, but choices have been made to allow docker support as well as a perfect match with BorgBackup recommendations. 

You'll find more information here in the documentation: https://borgwarehouse.com/docs/admin-manual/how-to-update/#whats-new-in-v2-
