### ISSUE TITLE
Wrong date in "Last Change"

### ISSUE THREAD

**Issue by p-rintz** [Ravinou/borgwarehouse#15]
Hi there,

I just realized that for some reason the "Last Change" date in the UI is off by a month.

So an update was done tonight on 2022-12-30, but the UI shows 2022-11-30:

![grafik](https://user-images.githubusercontent.com/13933258/210071578-271989f1-3b4f-44bc-a2ca-ee7ca623cbf3.png)

The date on the server is correct.

```
root@backup:~# date
Fri 30 Dec 2022 01:43:57 PM CET
```

Please say if you need any further information from me.

**Comment by Ravinou** [comment]
I'll check that !

**Comment by Ravinou** [comment]
You can `git pull` and `npm run build`.
