### ISSUE TITLE
Possible to access the same Borg Repo from multiple machines?

### ISSUE THREAD

**Issue by avephill** [Ravinou/borgwarehouse#154]
I'm new to borg and really appreciate this project, so thank you. But please forgive the possible basic question. 
I setup a borg repo through the borgwarehouse setup wizard. 
I backed up one of my computers to the remote borgwarehouse server, and now I want to access those files from my laptop. I have Vorta on my laptop, and when I enter the proper Repository URL and password it says it is unable to connect. I suspect that this is because of the ssh key that I input into borgwarehouse? Is it possible to enter two ssh keys so that two machines can access the content of the same repo? Thanks!

**Comment by Ravinou** [comment]
Hello and thank you for your interest @avephill 😉
Today, it is not possible to indicate a second key. The interface is very fast and allows you to replace the SSH key with your own while you do your recovery, for example. And then change your key again, in just a few clicks. 

I'll make a note of your comment in my cards, but it's a feature that would require a lot of integration. It's not impossible, but there's a lot to imagine around such a feature, both in terms of the UI and the backend. I'm keeping the idea anyway. Thanks

**Comment by avephill** [comment]
I didn't realize that you could switch out the ssh keys. I was able to switch out the ssh keys and access the repo from a different computer. Thanks so much!!
