### ISSUE TITLE
Manual import old repository: Storage used not updated - or what can be expected?

### ISSUE THREAD

**Issue by wokkieman** [Ravinou/borgwarehouse#156]
I've setup the latest docker version and I'm trying to manually import my old repositories according to https://borgwarehouse.com/docs/admin-manual/import-old-repo/

I can list the archives via borg list ssh and the REPOx id, but when opening borgwarehouse, I don't see updates to storage used. Is that as expected or should I still run something else?

Thanks for your efforts and sharing this!

**Comment by Ravinou** [comment]
Hi @wokkieman , set your cron : https://borgwarehouse.com/docs/admin-manual/docker-installation/#scheduled-tasks

**Comment by wokkieman** [comment]
ah thanks! read that page 6 times and forgot that part...
