### ISSUE TITLE
Spaces in passwords?

### ISSUE THREAD

**Issue by lightonflux** [Ravinou/borgwarehouse#164]
Just read the release notes for 2.2, but i haven't tested it. 
Does the "Spaces are now not allowed in login form." mean that spaces are disallowed for passwords?

**Comment by Ravinou** [comment]
Hi @lightonflux. The username of the login is concerned. You can, of course, put spaces in the password. My turn of phrase is confusing, so I'll update the release note.

**Comment by Ravinou** [comment]
release not is update. You can close the issue if you have no other questions about this.

**Comment by lightonflux** [comment]
Thank you very much for your work!
