### ISSUE TITLE
Server side prune

### ISSUE THREAD

**Issue by lightonflux** [Ravinou/borgwarehouse#165]
I would really like a server side prune. Is within the scope of borgwarehouse?
Especially with append-only this is quite important. And also for performance reasons.

**Comment by lightonflux** [comment]
Of course handling secrets is an issue, but for home users having unencrypted backups or storing the secrets on the server might be okay. For more security conscious setups borgwarehouse could communicate with a secrets provider. E.g. [Vault](https://developer.hashicorp.com/vault/api-docs) or [Bitwarden](https://bitwarden.com/help/service-accounts/).

**Comment by Ravinou** [comment]
Hi! For the time being, BorgWarehouse will only work **on the server side** and will not integrate the client side. There are many BorgBackup clients that do the job very well. You can configure Vorta or Borgmatic to manage backup pruning. This also enables e2e encryption, ensuring that the password never leaves the client side.

It's important to me that BorgWarehouse concentrates on server-side functionality, as this is its real added value. In short, **if a feature requires the backup encryption password, it's a client-side feature that won't be supported**.
