### ISSUE TITLE
Typo in systemd service description?

### ISSUE THREAD

**Issue by r748** [Ravinou/borgwarehouse#167]
In the [Debian deployment guide on how to setup a systemd service](https://borgwarehouse.com/docs/admin-manual/debian-installation/#setting-up-a-systemd-service-for-borgwarehouse) I think the line `WorkingDirectory=/home/borgwarehouse/borgwarehouse` is wrong and should rather read `WorkingDirectory=/home/borgwarehouse/app` instead?!

**Comment by Ravinou** [comment]
Hi, thank you, documentation is up to date.
