### ISSUE TITLE
[Debian] Repository path incorrect

### ISSUE THREAD

**Issue by r748** [Ravinou/borgwarehouse#168]
I have setup borgwarehouse 2.2.0 according to the Debian deployment guide. After creating a repository, when I copy the link via the button on the top right corner of the repository view, the path reads `ssh://borgwarehouse@myserver:myport/./328aa97e`. This leads to the repository being created under `/home/borgwarehouse/328aa97a` instead of `/home/borgwarehouse/repos/328aa97a`.

**Comment by Ravinou** [comment]
Hi @r748 , I've been using the docker version for several months now. I'm rebuilding BorgWarehouse in a Debian environment and I'll tell you how it goes.

**Comment by r748** [comment]
Thanks! Maybe this might also be related to issue #171...

**Comment by Ravinou** [comment]
I've just reassembled a Debian environment without Docker and I can confirm that the documentation and operation are OK ✅ !

![image](https://github.com/Ravinou/borgwarehouse/assets/39600829/3f05594c-2a91-48b7-9f73-27a78a29a028)

The command copied is the right one. And if you want to know the technical details, the authorized path is in the `authorized_keys` file. Your backups are located in `/home/borgwarehouse/repos` when you run one.

Did you run a backup and check where it was afterwards before opening this issue ? Or did you open this exit just by seeing the order in the quicksetting ? 😀

**Comment by r748** [comment]
Actually, I did perform a backup and the repository was created in the `/home/borgwarehouse` directory, as described above. However I found the problem now, thanks to you pointer to the `authorized_keys` file... I was using an incorrect SSH key on my client and therefore `command="cd /home/borgwarehouse/repos` wasn't applied.
