### ISSUE TITLE
No changes on the UI

### ISSUE THREAD

**Issue by shadowking001** [Ravinou/borgwarehouse#18]
Hello,

Thanks for this wonderful idea, it's been a while I was looking for a GUI for my borg backup, this software is pure pristine and I wish I could have a global view of my backup states, so BorgWarehouse seems totally fitting the purpose.

I have followed your instructions, and managed to run the automated scripts to my repos, doing my first dummy tries :

```
~ $ borg list ssh://06227990@db11sbx.xxxxx.ovh:22/./repo0
Enter passphrase for key ssh://06227990@db11sbx.xxxxx.ovh:22/./repo0:
ida-2023-01-26T11:00:06              Thu, 2023-01-26 11:00:07 [61488041c022246946b897aac85310e7e3eb73ce4eff73ba5249fa1452a264eb]
```

But I can't see anything on the GUI, as if there was nothing in the repository, plus the light keeps being red :

![image](https://user-images.githubusercontent.com/43928955/214822921-ae58d645-6ab0-4af1-a6c9-fa4af590974b.png)

Anything I could investigate on ?

**Comment by shadowking001** [comment]
EDIT : Sorry, I just had to wait for a while, it is okay now :
I had humped over the crontask too :

![image](https://user-images.githubusercontent.com/43928955/214824269-07917fcf-6b14-4233-96d2-ea7db4412c60.png)

**Comment by Ravinou** [comment]
Hello @shadowking001 ! 
First of all, a huge thank you for your encouragement ! I'm doing this on my own time and with passion so it's always heartwarming to read these kinds of comments :)

The status and storage updates are done with the cron job.

Have you placed this task in cron ? : 
```
* * * * * root curl --request POST --url 'http://localhost:3000/api/cronjob/checkStatus' --header 'Authorization: Bearer CRONJOB_KEY' ; curl --request POST --url 'http://localhost:3000/api/cronjob/getStorageUsed' --header 'Authorization: Bearer CRONJOB_KEY'
```

Doc ref for cronjob : https://borgwarehouse.com/docs/admin-manual/debian-installation/#cron-jobs 


If it's of for your cronjob, can you run the curl command in a terminal and show me the result please ?

Thanks

**PS : be careful to not sharing any personnal token in a paste**

**Comment by Ravinou** [comment]
> EDIT : Sorry, it is okay now, I had jumped over the crontask :
> 
> ![image](https://user-images.githubusercontent.com/43928955/214824269-07917fcf-6b14-4233-96d2-ea7db4412c60.png)

Great ! I can close this issue ? It's okay for you ?

**Comment by shadowking001** [comment]
Yes ! Thanks a lot
