### ISSUE TITLE
Repository for website

### ISSUE THREAD

**Issue by rugk** [Ravinou/borgwarehouse#221]
Hi I am looking for the GitHub repository for the website https://borgwarehouse.com/. I did not found a repo for it (just the software) though.

The thing is I was looking on contributing/improving the contrast here, as it is not really readable:
![grafik](https://github.com/Ravinou/borgwarehouse/assets/11966684/6e1b2348-65fe-40c9-a74c-ea3b86eff50b)

**Comment by Ravinou** [comment]
Thanks for your comment! The documentation is not on a public repository. But I've made the change, it's much more readable that way :)

![image](https://github.com/Ravinou/borgwarehouse/assets/39600829/9f831d4c-d3e2-41dc-9083-5b8ab18326e5)

**Comment by rugk** [comment]
Thanks, anyway why not put the doc on a public repo?

**Comment by Ravinou** [comment]
Because that's one more repository to maintain with contributions to manage. And also because, for the moment, I want to keep a certain amount of freedom over this doc. In particular, I'd like to have a logo for Borgwarehouse and do a little redesign at some point.

**Comment by rugk** [comment]
Hmm AFAIK contributors should be able to help. And maintenance can be simplified by using some CI/GitHub Pages or similar to automate deployment.
