### ISSUE TITLE
999(Go) is the maximum value.

### ISSUE THREAD

**Issue by YoSiJo** [Ravinou/borgwarehouse#24]
A couple of my repos are larger than 999G.
Is there a reason for this limit?
Would it be possible to set it higher or remove it altogether?

**Comment by Ravinou** [comment]
There's no reason, I think it's a limit that I used in my first test versions 😁. I will remove this as soon as possible. I'll do it quickly by tonight or tomorrow :)

**Comment by Ravinou** [comment]
I fixed it. You can update BorgWarehouse (doc is here for update if needed : https://borgwarehouse.com/docs/admin-manual/how-to-update/ ).

**Comment by YoSiJo** [comment]
Work fine by me. Big Thanks for the very fast solving.
