### ISSUE TITLE
Email notification rendered incorrectly on GMail

### ISSUE THREAD

**Issue by Forceu** [Ravinou/borgwarehouse#242]
I am using version 2.3.0 and the notification emails I receive are formatted incorrectly:

![image](https://github.com/Ravinou/borgwarehouse/assets/1593467/91b73dc3-dcaa-4b95-a3f5-eb81d7b80b00)

**Comment by Ravinou** [comment]
Hi! I don't use gmail, but I've just done a test on a gmail address and I see the same thing. I will correct the template so that it displays correctly on Gmail. 

Thanks for the feedback.

**Comment by Ravinou** [comment]
It seems that GMAIL does not support flexbox. A CSS property that must be over 10 years old by now. Is this funny or sad ?

**Comment by Forceu** [comment]
Thank you for the quick reply! I am quite surprised as well. Maybe this website is a good reference? https://www.caniemail.com/search/?s=Flex

**Comment by Ravinou** [comment]
I'm just on it yep : https://www.caniemail.com/search/?s=flex-direction 😭

**Comment by Ravinou** [comment]
Fixed ! The images were also in SVG, so not supported. The icon is now attached to the e-mail for better compatibility and deliverability. Everything is functional and will be in the next release (or available on "main"/docker:latest if you're in a hurry.)

I close the issue :) 

![image](https://github.com/Ravinou/borgwarehouse/assets/39600829/9ba6480e-a391-4acb-97ad-3034ceb96c65)

**Comment by Forceu** [comment]
Awesome! Thank you so much for the quick fix 🎉
