### ISSUE TITLE
Receiving too many notifications through sunrise

### ISSUE THREAD

**Issue by cmsj** [Ravinou/borgwarehouse#245]
Hey!

I've configured Sunrise to send notifications to Discord, and configured my borgwarehouse repos to notify me if no backup has been received in the last 24 hours. The settings UI indicates that I'll get a notification every 24 hours, but instead I seem to get one every minute:

<img width="553" alt="Screenshot 2024-06-24 at 09 35 13" src="https://github.com/Ravinou/borgwarehouse/assets/353427/31ca5984-10c1-4f8c-aa84-01d6f07bc0f7">

Did I miss something?

**Comment by Ravinou** [comment]
I can't reproduce your problem. Are you using docker ? 
Can you send me the contents of the config/repo.json file (hide your personal information if you wish, such as the public key, or the name of the repos).

**Comment by Ravinou** [comment]
Any news @cmsj ?
