### ISSUE TITLE
Storage used always 0

### ISSUE THREAD

**Issue by leouzz** [Ravinou/borgwarehouse#249]
I have recently installed the program and created two repositories. However, after performing the backup, the counter still shows 0 space used.

![image](https://github.com/Ravinou/borgwarehouse/assets/4449307/c7fb9237-3c50-4b5d-b6f1-98ed20c2525b)

**Comment by metrax** [comment]
Have you activated the cronjob?
https://borgwarehouse.com/docs/admin-manual/debian-installation/#cron-jobs

**Comment by leouzz** [comment]
thanks

**Comment by leouzz** [comment]
thanks
