### ISSUE TITLE
Cron job fails to execute correctly - getStorageUsed.sh

### ISSUE THREAD

**Issue by Aterfax** [Ravinou/borgwarehouse#25]
On Ubuntu 22.04.2 LTS (but I don't think Ubuntu is a problem here unless there's something weird going on with the Shell env), tried using the docs' specified cronjobs and got:

```
curl -sS  --request POST --url 'http://localhost:3000/api/cronjob/getStorageUsed' --header 'Authorization: Bearer REDACTED'
{"status":500,"message":"API error, contact the administrator."}
```

I think the current implementation of calling the getStorageUsed.sh script from NPM is causing issues with jc.

Calling  ` /home/borgwarehouse/borgwarehouse/helpers/shells/getStorageUsed.sh` directly works without errors but when calling via curl / the cronjob the journal logging shows:

```
Feb 26 02:30:01 server npm[37283]: Error: Command failed: /home/borgwarehouse/borgwarehouse/helpers/shells/getStorageUsed.sh
Feb 26 02:30:01 server npm[37283]: jc:  Error - Piped data and Magic syntax used simultaneously. Use "jc -h" for
Feb 26 02:30:01 server npm[37283]:              help.
Feb 26 02:30:01 server npm[37283]:     at ChildProcess.exithandler (node:child_process:419:12)
Feb 26 02:30:01 server npm[37283]:     at ChildProcess.emit (node:events:513:28)
Feb 26 02:30:01 server npm[37283]:     at maybeClose (node:internal/child_process:1091:16)
Feb 26 02:30:01 server npm[37283]:     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
Feb 26 02:30:01 server npm[37283]:   code: 100,
Feb 26 02:30:01 server npm[37283]:   killed: false,
Feb 26 02:30:01 server npm[37283]:   signal: null,
Feb 26 02:30:01 server npm[37283]:   cmd: '/home/borgwarehouse/borgwarehouse/helpers/shells/getStorageUsed.sh',
Feb 26 02:30:01 server npm[37283]:   stdout: '',
Feb 26 02:30:01 server npm[37283]:   stderr: 'jc:  Error - Piped data and Magic syntax used simultaneously. Use "jc -h" for\n' +
Feb 26 02:30:01 server npm[37283]:     '             help.\n'
Feb 26 02:30:01 server npm[37283]: }
```

I ended up resolving this with the following changes:

**/etc/sudoers.d/10-borgwarehouse**
```bash
#borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/jc du -s [[\:xdigit\:]]*
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/du -s [[\:xdigit\:]]*
```

**/home/borgwarehouse/borgwarehouse/helpers/shells/getStorageUsed.sh**
```bash
#!/bin/bash

# Shell created by Raven for BorgWarehouse.
# Get the size of all repositories in a JSON output.
# stdout will be an array like : 
# [
#     { size: 32, name: '10e73223' },
#     { size: 1155672, name: '83bd4ef1' },
#     { size: 112, name: '635a6f8b' },
#     { size: 32, name: 'bce68e87' },
#     { size: 44, name: 'e4c04552' },
# ];

# Exit when any command fails
set -e

# Use jc to output a JSON format with du command
cd /var/borgwarehouse
#sudo jc du -s *
sudo /usr/bin/du -s * | jc --du
```

**Comment by Ravinou** [comment]
Thanks for your feedback. I will test on Ubuntu 22.04.2 to try to reproduce your mistake.

**Comment by Ravinou** [comment]
@Aterfax Can you tell me if it's Ubuntu with desktop env or if it's ubuntu server image without gui ? Thank you

**Comment by Aterfax** [comment]
Fairly sure it is Ubuntu server with XFCE on it, but is used 99% of the time headlessly.

**Comment by Ravinou** [comment]
Thank you, it is to allow me to reproduce the error as well as possible. I'm doing some tests today and I'll let you know.

**Comment by Ravinou** [comment]
I was able to reproduce the bug. It's still strange... especially since the script runs normally when I launch it manually, it causes an error only when executed by node.

I think this is a version specific problem with `jc`, I don't see any other explanation:
- Debian 11 - jc 1.14.3 ✅
- Fedora 37 - jc 1.22.5 ✅
- Ubuntu Server 22.04 - jc 1.17.3 ❌

Thank you @Aterfax for looking for the solution and sharing it ! I'm studying it in a branch if the solution has no impact on Debian and Fedora. If it's ok, I'll modify the code to improve the compatibility with Ubuntu Server.

@p-rintz Can you validate the change in sudo permissions please ? 🙏

**Comment by p-rintz** [comment]
Its one of the commands that will be gone with the 2.0 release. (from the sudoers list)

For now, it should be fine. It doesn't really change anything from before.

**Comment by Ravinou** [comment]
Thank you @p-rintz I'll test it. And if it is problematic it will be removed in v2 anyway so it is not very important.
