### ISSUE TITLE
Set-up on CapRover

### ISSUE THREAD

**Issue by Firesphere** [Ravinou/borgwarehouse#258]
I'm trying to set up BorgWarehouse on a CapRover server (Using docker).
Despite setting up the volumes and the environment variables, it doesn't seem to be willing to start. And the logs are empty (The container doesn't even seem to start)

**Comment by Ravinou** [comment]
Hi @Firesphere , I don't know what is CapRover and I really need more context to help you. Do you have log somewhere ? From docker ?

**Comment by Firesphere** [comment]
Apologies :)
CapRover is a Docker container hosting system. I simply give it some environment variables and an image, to get things started.
However, it just doesn't start, as in my original issue post, the logs are literally empty, nothing seems to be going.

My procedure:
- Create a new docker environment
- Add the environment variables
- Add the mountpoints for config/data/etc.
- Tell CapRover to pull the image

It simply returns blank :'(

**Comment by Ravinou** [comment]
Hi, were you able to solve your problem? I'm not really familiar with CapRover but if I can help you, please don't hesitate to give me more information.
