### ISSUE TITLE
Mounted ext4 for repos location

### ISSUE THREAD

**Issue by mnestor** [Ravinou/borgwarehouse#267]
I've mounted an ext4 partition to my repos directory. This contains the lost+found directory now causing issues when updating storage. As this is something to ignore anyway when getting the directory sizes it seems that placing

`GLOBIGNORE="lost+found"` 

in the `getStorageUsed.sh` should be safe to do?

This way the directory is ignored preventing an error dumping to stderr causing the script call to think it failed and not process results.

**Comment by Ravinou** [comment]
Thanks for the suggestion, I'll take a look.

**Comment by Ravinou** [comment]
Release in 2.4.2 just now.
