### ISSUE TITLE
Issue deploying BorgWarehouse on Unraid

### ISSUE THREAD

**Issue by davidlebr1** [Ravinou/borgwarehouse#270]
Hello, 

First, I would like to say thank you for this project. I'm really looking forward in testing it. I have been trying to deploy it on Unraid but unfortunately I have an error and I'm not sure where to start or how I can fix it. 

I have the following setting:
![image1](https://github.com/user-attachments/assets/003bd739-88dd-41e6-ad34-8d92838bcb2a)
![image2](https://github.com/user-attachments/assets/45f9d2d4-15c5-47ca-b176-0fb2b1eff428)

**Comment by davidlebr1** [comment]
Solved, I deployed on Unraid by manually adding the docker compose and I set the permission on the folder to the same that is set in the docker-compose environment file which is 1001:1001

**Comment by Ravinou** [comment]
> First, I would like to say thank you for this project.
Thanks for the encouragement, which gives me the energy to work on it ❤️

And thank you again @davidlebr1 for sharing solution for other users on "Unraid" solution 👍

**Comment by uchagani** [comment]
@davidlebr1 can you explain a bit more how you got this working?

**Comment by That-Dude** [comment]
> Solved, I deployed on Unraid by manually adding the docker compose and I set the permission on the folder to the same that is set in the docker-compose environment file which is 1001:1001

Can you explain how you did this? I have to docker compose setup like this:

```
services:
  borgwarehouse:
    container_name: borgwarehouse
    # If you want to build the image yourself, uncomment the following lines and comment the image line
    #build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #       - UID=${UID}
    #       - GID=${GID}
    image: borgwarehouse/borgwarehouse
    user:  UID:1001:GID:1001'
    ports:
      - '3000:3000'
      - '3222:22'
    volumes:
      - /mnt/user/appdata/borhwarehouse/config:/home/borgwarehouse/app/config
      - /mnt/user/appdata/borhwarehouse/ssh:/home/borgwarehouse/.ssh
      - /mnt/user/appdata/borhwarehouse/ssh_host:/etc/ssh
      - /mnt/user/backups/borgwarehouse/repos:/home/borgwarehouse/repos
      - /mnt/user/appdata/borhwarehouse/temp:/home/borgwarehouse/tmp
      - /mnt/user/appdata/borhwarehouse/logs:/home/borgwarehouse/logs

```
```
But I get this error:
 ⠙ Container borgwarehouse  Starting
Error response from daemon: unable to find user UID: no matching entries in passwd file
```
