### ISSUE TITLE
Built in automated backups?

### ISSUE THREAD

**Issue by simen64** [Ravinou/borgwarehouse#275]
I have been trying out BorgWarehouse, and Its a good tool with a good UI for managing different repo's on different servers. aswell as quickly adding repos. However the lack of a built in automatic backup feature is kinda a dealbreaker for me. When i first have a webUI thats what i want to use, having to have scripts and other automation tools aswell as borgwarehouse just adds unnecessary parts which could break, and more complexity. Is there a plan for adding a built in automation feature?

**Comment by Ravinou** [comment]
Hi 😀

Like many tools, BorgBackup is designed on a client/server model. BorgWarehouse is [server-side only](https://borgwarehouse.com/docs/prologue/introduction/), and **always will be**. There are plenty of BorgBackup clients like [Vorta](https://vorta.borgbase.com/) or [PikaBackup](https://apps.gnome.org/fr/PikaBackup/) with which you can automate your backups through a UI. 

I hope I've answered all your questions, and I'll now close this issue.

**Comment by simen64** [comment]
Okay thank you
