### ISSUE TITLE
Docs: Debian Deployment

### ISSUE THREAD

**Issue by sigio** [Ravinou/borgwarehouse#290]
As requested via mastodon:

in https://borgwarehouse.com/docs/admin-manual/debian-installation/

• For ED25519 :
ssh-keygen -lf /etc/ssh/ssh_host_ecdsa_key | awk '{print $2}'

This comment should say ecdsa key :)

**Comment by sigio** [comment]
Also maybe add some info somewhere on running the service on an alternative port, I ran into issues where port 3000 was already in use, so I had to add 'next start -p 3022' in package.json.
Also changed the cronjob to juse run every 5 minutes, which is already overkill if backups run at most every hour.

**Comment by Ravinou** [comment]
Thanks, I've removed the reference to ECDSA as it's not currently supported in BorgWarehouse anyway. The port is already mentioned in the FAQ.

Thank you for your issue :)
