### ISSUE TITLE
How to reset the WebUI Admin password

### ISSUE THREAD

**Issue by ssafhi** [Ravinou/borgwarehouse#313]
Dears,

There are no details about resetting the admin password in the documentation (Debian install), may you kindly assist me with how to do that?

BR
Sami

**Comment by Ravinou** [comment]
Hi @ssafhi !
To restore the "admin" default password, you can edit the file `config/users.json` and update the 'password' key with the value : '$2a$12$20yqRnuaDBH6AE0EvIUcEOzqkuBtn1wDzJdw2Beg8w9S.vEqdso0a'

Let me know if it's ok for you.

**Comment by ssafhi** [comment]
> Hi @ssafhi ! To restore the "admin" default password, you can edit the file `config/users.json` and update the 'password' key with the value : '$2a$12$20yqRnuaDBH6AE0EvIUcEOzqkuBtn1wDzJdw2Beg8w9S.vEqdso0a'
> 
> Let me know if it's ok for you.

Thank you so much, this is working like a charm.

BR
  Sami
