### ISSUE TITLE
Status "500" : Error on getting storage, contact the adminstrator

### ISSUE THREAD

**Issue by shadowking001** [Ravinou/borgwarehouse#32]
Hello,

I'm trying to find out why my repo status is not calculating the storage used when running manually the curl command :

`curl --request POST --url 'http://localhost:3000/api/cronjob/checkStatus' --header 'Authorization: Bearer CRONJOB_KEY' ; curl --request POST --url 'http://localhost:3000/api/cronjob/getStorageUsed' --header 'Authorization: Bearer CRONJOB_KEY'`

The status is updated, going to green light, but logs say :

`{"success":"Status cron has been executed."}{"status":500,"message":"Error on getting storage, contact the administrator."}`

Running it through a crontask, neither the status or the storage are updated, which is probably related to another issue.

Some details of the setup :

- crontask added to root user (since executed by root)
- I changed the hostname of my vm meanwhile the first setup, thus I have modified the NEXT_PUBLIC_HOSTNAME accordingly. Even though this variable doesn't seem to make a rebuild mandatory, I went through the full npm circle to ensure that the change is taken into account.

**Comment by Ravinou** [comment]
Hi, can you check if the file : `/etc/sudoers.d/10-borgwarehouse` is strictly equal to "https://github.com/Ravinou/borgwarehouse/blob/main/docs/sudoers/10-borgwarehouse" ?

If the sudoers file is okay : 
- stop your BorgWarehouse service
- Launch the application manualy with "borgwarehouse" user : `su borgwarehouse` and `npm run start` (be sure to be inside the application folder).
- Now, you have direct log so you can trigger the getStorageUsed and show a more detailled error : `curl --request POST --url 'http://localhost:3000/api/cronjob/getStorageUsed' --header 'Authorization: Bearer CRONJOB_KEY`

**Comment by shadowking001** [comment]
Sorry for the delay, I've been really busy these last weeks at work.
Working as intended now with the modification in the sudoers file. 👍
