### ISSUE TITLE
Web UI does not show consumed backup space and last backup status

### ISSUE THREAD

**Issue by fibrinogen** [Ravinou/borgwarehouse#347]
Hi, it's me again.
Again: Thank you for creating free software!

Now, that the repositories are created in the right place, the WEB UI does not show the last backup and also not the consumed space. Do you have any hints?

The installation path is: /home/borgwarehouse
The backup medium is an USB disk, that is mounted on /media/backup and that directory is linked to /home/borgwarehouse/repos 
The directory /media/backup is owned by borgwarehouse
I'm using the borgwatehouse wizard to get the commands and date to create a backup using Vorta from a remote machine and that works. The repo is created.

Output of an ls inside the repos directory:
borgwarehouse@hpt630thinclient:~/repos$ ls -l
drwxr-xr-x 5 borgwarehouse borgwarehouse  4096 Nov  9 13:44 ./
drwxr-xr-x 7 root          root           4096 Okt  1 22:14 ../
drwx------ 3 borgwarehouse borgwarehouse  4096 Nov  9 13:55 33dce6f2/
drwx------ 3 borgwarehouse borgwarehouse  4096 Nov  9 15:51 8c351dd8/
drwx------ 2 root          root          16384 Nov 17  2018 lost+found/

![Screenshot from 2024-11-09 23-26-27](https://github.com/user-attachments/assets/7b29e9d2-a29c-4ec1-96dd-736fe50b6731)

![Screenshot from 2024-11-09 23-27-39](https://github.com/user-attachments/assets/8909a105-046d-4c1e-92eb-66895ffd3bae)

**Comment by Ravinou** [comment]
Hi again 😀

Did you set your [schedule tasks](https://borgwarehouse.com/docs/help/faq/#i-dont-see-the-status-or-storage-updates) ? 
- Cron for [Docker installation](https://borgwarehouse.com/docs/help/faq/#i-dont-see-the-status-or-storage-updates)
- Cron for [baremetal Debian installation](https://borgwarehouse.com/docs/admin-manual/debian-installation/#cron-jobs)

**Comment by fibrinogen** [comment]
That was good hint.
Status works, but storage does not.

sudo -u borgwarehouse -g borgwarehouse -- curl --request POST --url 'http://localhost:3000/api/cronjob/checkStatus' --header 'Authorization: Bearer 1233333=' ; curl --request POST --url 'http://localhost:3000/api/cronjob/getStorageUsed' --header 'Authorization: Bearer 1233333='
{"success":"Status cron has been executed."}{"status":500,"message":"Error on getting storage, contact the administrator."}

**Comment by Ravinou** [comment]
A 500 error necessarily generates a log in borgwarehouse. I need the details of this log to help you. Can you please provide it?

For logs on barematal installation : [see this post.](https://github.com/Ravinou/borgwarehouse/issues/287#issuecomment-2322968588). For docker, it's in your volume.

**Comment by fibrinogen** [comment]
I did a baremetal installation and I started just using: npm run start
Where are logs supposed to be in this case?
There is nothing written on the console, when trying to get the repo space usage.

borgwarehouse@hpt630thinclient:~/app$ npm run start
> borgwarehouse@2.4.1 start
> next start
  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000
 ✓ Starting...
 ✓ Ready in 962ms

**Comment by Ravinou** [comment]
Is the ‘jc’ package installed on your machine? I've managed to remove this dependency in the next release, but if you're on tag 2.4.1, you need the ‘jc’ package to retrieve storage. This may be why you have a 500.

**Comment by Ravinou** [comment]
Given that you have a baremetal installation, can you launch the script `helpers/shells/getStorageUsed.sh` manually please ? You will have the exact error :+1:

**Comment by fibrinogen** [comment]
Sorry for bothering you with these kind of problems. There was a lost+found directory inside the repo that was not owned by borgwarehouse. And that was included in the du command.

**Comment by Ravinou** [comment]
The lost+found directory will be ignored in the next release, someone else report this in #267 

I hope that everything works fine for you know :)
