### ISSUE TITLE
[question] When do you plan to wrap up version 2?

### ISSUE THREAD

**Issue by tukanos** [Ravinou/borgwarehouse#35]
Hello,

I'm considering on deploying borgwarehouse.  I wonder when do you plan on v2 to came out?  I don't want to roll out a deployment  only to find out that in 2 weeks there is a new version.  I'm in no hurry.

Thank you.

**Comment by Ravinou** [comment]
Hi, @tukanos ! 
I plan to deploy BorgWarehouse v2 once BorgBackup v2 is released. There is no release date communicated by the BorgBackup developers. Currently, BorgBackup v2 has passed alpha and is now in beta (https://github.com/borgbackup/borg/issues/6602)

Between their v2 release, my BorgWarehouse impact study and the release of BorgWarehouse v2, I don't think it will be before 2024. You have plenty of time to use BorgWarehouse in its current version in my humble opinion.

**Comment by tukanos** [comment]
Hi @Ravinou ,

Thank you for the details.  That gives me rough idea of the plan.  I'll then play around with the BorgWarehouse at the current state.
