### ISSUE TITLE
Used storage not increasing in UI

### ISSUE THREAD

**Issue by mregni** [Ravinou/borgwarehouse#357]
Hi

I set up the borgwarehouse container and manually made a borg backup with "borg create" like mentioned in the bordwarehouse setup wizard. Backup seems to be working but the UI itself does not mention I'm using 10% of used repo space for some reason.
![image](https://github.com/user-attachments/assets/b98b505a-d8b9-40b9-835c-277afb58dca1)

The /home/borgwarehouse/repos folder is mapped to a ZFS pool. In the screenshot you can see that the backup is placed in the zpool (used space is 444Gb and was around 110 before backup).
![image](https://github.com/user-attachments/assets/78d726d9-cac4-416f-a31b-ee4ad556e525)

borg list command returns the proper "photos" backup as well and I can mount it.

Any idea why the used storage is not increased for me?

**Comment by ruohki** [comment]
same issue

**Comment by maxhamon** [comment]
You need to add a cron job as mentioned at https://borgwarehouse.com/docs/admin-manual/docker-installation/

**Comment by mregni** [comment]
You sir, are a hero!! :-D

**Comment by Ravinou** [comment]
Thank you @maxhamon for this contrib to help 🙏

**Comment by ruohki** [comment]
had a typo in my cron config.
