### ISSUE TITLE
Borgwarehouse on TrueNAS scale

### ISSUE THREAD

**Issue by ToeiRei** [Ravinou/borgwarehouse#365]
TrueNAS Scale recently dropped their mini-kubernetes and went for docker-compose which - in theory - is a nice idea until you had 3rd party repos.

Having a nice UI like borgwarehouse would be a nice addition - so I thought.

I created a new 'app' which is just a fancy name for a docker container. Settings as described in the docker-compose while adding the .env part as Environment variables. Due to the UID-Problems I created a user named 'borgwarehouse' on the TrueNAS and gave it the UID of 1001 which the container was running on and assigned existing directories as volumes.

Good news: The container starts up and the web interface gets displayed and I can - in theory - add a repo.

Bad news: SSH connections are not possible with borg

sshd log:
```
2024-12-07T17:30:12.120744+01:00 sshd Server listening on 0.0.0.0 port 22.
2024-12-07T17:30:12.120788+01:00 sshd Server listening on :: port 22.
2024-12-07T17:33:12.940877+01:00 sshd Connection closed by xxxxx port 54314 [preauth]
2024-12-07T17:33:35.412614+01:00 sshd maximum authentication attempts exceeded for borgwarehouse from xxxxx port 39152 ssh2 [preauth]
2024-12-07T17:33:35.412657+01:00 sshd Disconnecting authenticating user borgwarehouse xxxxx port 39152: Too many authentication failures [preauth]
```

authorized_keys:
```
command="cd /home/borgwarehouse/repos;borg serve --restrict-to-path /home/borgwarehouse/repos/7624b034 --storage-quota 100G",restrict ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICuhqhmd2UUgWKqIQM08tF8kvmMW8F6a
Tn5IXY8Q8LNe
```

Anything I can do to resolve that issue?

**Comment by Ravinou** [comment]
When you say : "SSH connections are not possible with borg" - Do you try to backup with a borgbackup client or do you try to remotely access with SSH ?

**Comment by ToeiRei** [comment]
SSH port is open but borg cannot connect:

```
borg init -e repokey-blake2 ssh://borgwarehouse@borg.host:2222/./xxxx
Remote: Received disconnect from xxx port 2222:2: Too many authentication failures
Remote: Disconnected from xxx port 2222
Connection closed by remote host. Is borg working on the server?
```

**Comment by Ravinou** [comment]
If your key is right, then it looks like a file rights problem. I don't know your TrueNas installation environment at all. But it could be a problem with volume rights. That could cause this error message.

**Comment by ToeiRei** [comment]
Well, if the permissions would be wrong, sshd would complain about invalid permissions on the file itself (.ssh and authorized_keys need the exact ownership/perms) which I have seen before on that installation.

**Comment by ToeiRei** [comment]
I did some digging and switched off the MaxAuthTries in the sshd_config and ended up with a backup!
