### ISSUE TITLE
NextJS throws uncaught exception on copy-to-clipboard

### ISSUE THREAD

**Issue by ToeiRei** [Ravinou/borgwarehouse#366]
As stated in the title: 

"Uncaught (in promise) TypeError: navigator.clipboard is undefined" shows up in the js console of the browser when trying to copy the link to backup to (ssh://....) using the button provided.

**Comment by Ravinou** [comment]
Are you in HTTPS on your installation ?

**Comment by ToeiRei** [comment]
Not yet as I did not have a ssl cert set up yet.

**Comment by Ravinou** [comment]
Okay, I know that navigators don't allow access to clipboard in HTTP, for security reason. So this functionnality will work only in HTTPS.

**Comment by ToeiRei** [comment]
Is there a possibility to make the field permanently visible so people who do not (yet) run https can easily copy (ctrl + c) the text?
