### ISSUE TITLE
REPOSITORY: Invalid location format

### ISSUE THREAD

**Issue by gummipunkt** [Ravinou/borgwarehouse#37]
I've created a repository, after that I copied the command:
"borg init -e repokey-blake2 ssh://61000xx8@https://sub.domain.tld:22/./repo1"

Console Output on the client side:
borg init: error: argument REPOSITORY: Invalid location format: "ssh://61000xx8@https://sub.domain.tld:22/./repo1"

**Comment by Ravinou** [comment]
Hi @gummipunkt, there should be no `https://` in your command. This means that the environment variable is incorrectly configured. It is the FQDN that must be indicated so you must remove the `https://` from your `NEXT_PUBLIC_HOSTNAME` variable.

Remember to rebuild your application after the modification and everything should work :)

Check documentation here for more detail : https://borgwarehouse.com/docs/admin-manual/debian-installation/#configure-application-environment-variables
