### ISSUE TITLE
cannot enter email "Your email is not valid"

### ISSUE THREAD

**Issue by hugalafutro** [Ravinou/borgwarehouse#38]
Hi, 
very excited to try out your app, been looking for some sort of web frontend for borg for some time. Looking forward to docker deployment.

When I enter my email in the admin page I get the error "Your email is not valid". For obvious reasons I don't wanna put my email in public space, but perhaps it is something in the pattern of it that makes in not get accepted.

The pattern of the email is as follows:
1 letter 1 number @ 3 letters dash mail.net so for example `j4@lol-mail.net` would be email of same pattern as mine. Hope that makes sense.

Thanks for any idea.

**Comment by Ravinou** [comment]
Hi @hugalafutro ! It's fixed ! The regex on the backend did not accept "-" in domains. This is fixed :)

You can update your BorgWarehouse [by following this doc](https://borgwarehouse.com/docs/admin-manual/how-to-update/) if you need :+1:
