### ISSUE TITLE
TrueNas and NFS Share

### ISSUE THREAD

**Issue by hugalafutro** [Ravinou/borgwarehouse#39]
Hi,
backups and everything else works, the cron command (runs from root cron) works if I run it manually I get `{"success":"Status cron has been executed."}{"success":"Storage cron has been executed."}`, but the status is red and last change never changes.

![image](https://github.com/Ravinou/borgwarehouse/assets/30209689/55875c26-6e5b-4e1f-9fce-69d08fb89d99)

I presume this then would not trigger the notifications on missed backups as well?

**Comment by hugalafutro** [comment]
It actually causes sending the emails out even though the backups still happen correctly (I use borgmatic + healthchecks to confirm). Let me know if you need some logs or something.

**Comment by hugalafutro** [comment]
```
[
  {
    "user": "root",
    "lastSave": 1684969987
  },
  {
    "user": "root",
    "lastSave": 1685048428
  },
  {
    "user": "root",
    "lastSave": 1685048423
  },
  {
    "user": "root",
    "lastSave": 1685048462
  },
  {
    "user": "root",
    "lastSave": 1685048543
  },
  {
    "user": "root",
    "lastSave": 1685048510
  },
  {
    "user": "root",
    "lastSave": 1685048421
  }
]
```

Not sure if relevant, but my user is named admin (i didn't change the default) not root. The cron job runs as root, should it run as borgwarehouse user ?

**Comment by Ravinou** [comment]
There's a problem with your users.
When you create a repository on borgwarehouse, it creates a different unix user for each repo (this ensures perfect security isolation for each repository).
It's **not normal** for the user (in this object) to be root every time, which is why you don't get status feedback.

This is what the return command should look like, one different user for each : 
```sh
 [
   {
     "user": "09d8240f",
     "lastSave": 1668513608
   },
   {
     "user": "635a6f8b",
     "lastSave": 1667910810
   },
   {
     "user": "83bd4ef1",
     "lastSave": 1667985985
   }
 ]
```
Each user for each repo must be different.

Do you follow [the documentation](https://borgwarehouse.com/docs/admin-manual/debian-installation/) to install it ? 

> Not sure if relevant, but my user is named admin (i didn't change the default) not root. The cron job runs as root, should it run as borgwarehouse user ?

Your user name for the borgwarehouse interface is irrelevant ;). And you're free to use the cron with any user, as it's just an API call :+1:

**Comment by hugalafutro** [comment]
I've followed the installation guide to the letter, twice. 

First install was with all variables proper fqdn's, only after that I realized it's uploading via internet even from local and I couldn't do user@ip/repo, so I reinstalled with the NEXT env changed to local ip so I can do both `user@fqdn:remote_port/repo` an `user@local_ip:local_port/repo`.

But the statuses were red and last change empty form the 1st install.

**Comment by Ravinou** [comment]
A friend runs it since months on Raspberry, no problem :+1: 

Can you show me the result of `ls -la /var/borgwarehouse` please ? Thanks

**Comment by hugalafutro** [comment]
ooh, could the problem be the `/var/borgwarehouse/` is a nfs share with mapall set to root which I do without thinking on all nfs shares because I'm to lazy for the permissions? 😄 
```

pi@pi-docker:~ $ ls -la /var/borgwarehouse
total 72
drwxr-xr-x  9 root     root             9 May 26 00:18 .
drwxr-xr-x 15 root     root          4096 May 24 18:31 ..
drwxr-x---  4 0711603a borgwarehouse    8 May 24 12:13 0711603a
drwxr-x---  4 1741362c borgwarehouse    8 May 24 02:43 1741362c
drwxr-x---  4 174bed92 borgwarehouse    8 May 26 00:18 174bed92
drwxr-x---  4 26d812b0 borgwarehouse    8 May 24 02:32 26d812b0
drwxr-x---  4 be8ea59b borgwarehouse    8 May 24 11:45 be8ea59b
drwxr-x---  4 d96d2bf0 borgwarehouse    8 May 24 11:36 d96d2bf0
drwxr-x---  4 ee40e502 borgwarehouse    8 May 24 02:37 ee40e502
```

![image](https://github.com/Ravinou/borgwarehouse/assets/30209689/008903aa-26c3-47d7-ab39-aa880405723b)

**Comment by Ravinou** [comment]
Okay, that's the point :D !

Users are well created, good news. So now, if you launch the command `ls -la /var/borgwarehouse/*/repos/*/integrity*` do you have for each line, a owner/group like : 

```
-rw------- 1 01d7fed7 01d7fed7 190 Mar 15 09:13 /var/borgwarehouse/01d7fed7/repos/repo6/integrity.5
-rw------- 1 5119e9ap 5119e9ap 190 Mar 22 10:03 /var/borgwarehouse/5119e9ap/repos/repo5/integrity.6
```

Owner must be the same as the folder name /var/borgwarehouse/owner. Do you have a result like this ? 

Thanks

**Comment by Ravinou** [comment]
I really think that the problem is your `mapall root`. It's impossible for BorgWarehouse to know which repository belongs to which unix user if you mapall with root.

**Comment by hugalafutro** [comment]
bingo
```
-rw------- 1 root root 190 May 26 14:17 /var/borgwarehouse/0711603a/repos/repo10/integrity.76
```
so If I 
- `sudo service borgwarehouse stop`
- `sudo umount /ver/borgwarehouse`
- remove the mapall root on truenas & restart nfs service
- `mount /var/borgwarehouse`
- `chown -R 0711603a:0711603a /var/borgwarehouse/0711603a` with each user for each repo
- `sudo service borgwarehouse start`
it should work yea?

**Comment by Ravinou** [comment]
`chown -R 0711603a:borgwarehouse /var/borgwarehouse/0711603a && chown -R 0711603a:0711603a /var/borgwarehouse/0711603a/repos/repo10/*`

**Comment by hugalafutro** [comment]
I'm thinking create fresh share start from scratch, I removed the mapall root on the nas, but then I was getting errors regardless as what user I ran the chown. It's my fault for not thinking

I'll report back once I recreate 1 repo on new share.

**Comment by Ravinou** [comment]
Indeed, I think this is a specific case in your architecture. But it could be interesting for other users, so don't hesitate to come back here when it's good and we'll close the issue :)

So you're using TrueNas?

**Comment by hugalafutro** [comment]
Yup Truenas Scale, and since it's only me accessing over nfs (others just consume media via smb on win machines), I usually keep permissions as mapall root on nfs for the sake of convenience.

**Comment by hugalafutro** [comment]
Success!
![image](https://github.com/Ravinou/borgwarehouse/assets/30209689/1d445bf7-d484-4bc3-835a-6a7219148d0d)

Turns out, I had to do the exact opposite on the share and do maproot root to prevent root becoming nobody thus failing the sudo commands, because nfs default is to squash root:

_(note: this is from a general linux forum not truenas specific)_
> By default the root_squash export option is turned on, therefore NFS does not allow a root user from the client to perform operations as root on the server, instead mapping it to the user/group id specified by anonuid and anongid options (default=65534).

took some screenshots maybe for someone with same issue in future

permissions on the truenas dataset:
![image](https://github.com/Ravinou/borgwarehouse/assets/30209689/c9ed667e-1be2-4502-87fa-a35e06f8eb86)

security on the truenas nfs share
![image](https://github.com/Ravinou/borgwarehouse/assets/30209689/d3fed1c7-f607-442f-ab2f-4e4ef62a967e)
![image](https://github.com/Ravinou/borgwarehouse/assets/30209689/91051d49-07ee-4d34-991e-afbeb1877e07)
