### ISSUE TITLE
How to install for an existing borg repository

### ISSUE THREAD

**Issue by PierrickBrun** [Ravinou/borgwarehouse#4]
Hi and thanks for this work !

I this this would be great if there was a doc explaining how to install borgwarehouse on top of an existing borgbackup server.

Also I had trouble understanding how it works internally so it could be great to explain how it communicates with borg (I think it sends CLI commands, isn't it ?)

From what I understand borgwarehouse have to be installed on the same server as the borg server, I think it would improve the comprehension for some people to put it in the doc.

Many thanks for this project, it looks awesome !

**Comment by Ravinou** [comment]
Hi @PierrickBrun and thank you for your feedback 🤗

> how it works internally

The JS application uses **bash system scripts that I wrote and placed in** `helpers/shells`. 
I haven't had personal time **yet** to write in the documentation about how the application works. But if you want, you can already read the code comments in the shells. I have tried to comment the code of these scripts as well as possible 🙏

> From what I understand borgwarehouse have to be installed on the same server as the borg server, I think it would improve the comprehension for some people to put it in the doc.

I have added your comment [to the FAQ](https://borgwarehouse.com/docs/help/faq/#does-borgwarehouse-have-to-be-installed-on-the-same-server-as-borgbackup-)

> How to install for an existing borg repository ?

I don't really have a ready-made answer to this question, although I have asked myself.

Actually, if you create your repositories on the interface, and then move the complete content of old repositories into the filesystem (be careful to respect the user folder), I think it's perfectly functional.

I'll keep this in mind for testing when I have more time. But if you do it on your side, don't hesitate to send me a feedback :)
