### ISSUE TITLE
Add support local/remote repo in generated commands

### ISSUE THREAD

**Issue by hugalafutro** [Ravinou/borgwarehouse#40]
Hi,
when I first deployed borgwarehouse I realized using fqdn in the `NEXTAUTH_URL` generates the repos as `user@fqdn:remote_port/repo`, which is fine for remote machines, but when used for machines that were on local lan they were backing up over my slow internet instead of lan.

My borgwarehouse instance is behind `nginx-proxy-manager` reverse proxy. In router I have random `remote_port` forwarded to ssh port of machine where borgwarehouse runs

So I changed `NEXTAUTH_URL` to the ip where borgwarehouse runs, rebuilt and now:
- when I back up remote machine - nothing changes - I paste in commands as borgwarehouse generates them
- BUT when I back up local machine, I have to manually change in every command the `@fqdn:remote_port` part to `@local_ip:local_port`

I propose a toggle in the repo config to designate it "local". Extract the ip from `NEXTAUTH_URL` variable. A new env var `NEXT_LOCAL_SSH_SERVER_PORT` in the `.env.local` (I've no idea if it current ssh port cannot be retrieved automatically in case 22 is not used, if so then not needed).

Then if toggled, would display all the generated commands for the selected repo as `...@local_ip:${NEXT_LOCAL_SSH_SERVER_PORT}`

Let me know what you think.

**Comment by Ravinou** [comment]
Hi ! 
Thanks, it's a good idea, I'm on it, I added a checkbox. I told you when I publish it in next few days.

![image](https://github.com/Ravinou/borgwarehouse/assets/39600829/dd33d074-1cb5-4f5e-8a21-d06e90771645)

**Comment by Ravinou** [comment]
Hi @hugalafutro , I've finished integrating your feature request and updating the related documentation.

About this new feature, you can : 
- Consult the admin documentation [here](https://borgwarehouse.com/docs/admin-manual/debian-installation/#configure-application-environment-variables)
- Consult the user documentation [here](https://borgwarehouse.com/docs/user-manual/repositories/#generates-commands-for-use-over-lan)
- Apply the update to your BorgWarehouse by [following this doc](https://borgwarehouse.com/docs/admin-manual/how-to-update/)

Let me know if you like it ! 🚀

**Comment by hugalafutro** [comment]
Very nice, works exactly as I imagined. Thanks for considering my idea and for implementing it!

**Comment by ashpath22** [comment]
Hi!
please can anyone help me?
i'm a new user of borgwarehouse and i want to know how to create a remote directory for my backup (i want to backup my data in another server)
can someone help me step by step?

**Comment by hugalafutro** [comment]
@ashpath22
make a share on nas, expose it via nfs, mount it via `/etc/fstab` on the machine where you run borgwarehouse:
```
192.168.1.181:/mnt/pool2/borgwarehouse      /mnt/borgwarehouse     nfs      rw,user,x-systemd.automount,x-systemd.mount-timeout=10,defaults,soft,_netdev       0      0
```

then in borgwarehouse `.env` define it as the repo for borgwarehouse
```
BORG_REPOSITORY_PATH=/mnt/borgwarehouse
```

**Comment by ashpath22** [comment]
@hugalafutro 
i got 2 servers. one i want to back up (borgwarehouse is install on it. the other one is the server that i want to store the back up made by the first one. i want to configure borgwarehouse to do this 
in one sentence i want to back up a server to another server via borgwarehouse

**Comment by ashpath22** [comment]
so explain how you do that 
i just want to know the process with a remote repository via borgwarehouse

**Comment by hugalafutro** [comment]
@ashpath22 I mean I did in the first post. 
you have NAS and machine with borgwarehouse.
on NAS make a nfs share
mount it on the machine where borgwarehouse runs
point the environment variable at it.

docker doesn't care if it's nfs /smb share or usb drive or aprtition on internal disc, whatever is mounted where BORG_REPOSITORY_PATH points, that's where borgwarehouse will create all the backups it will produce

**Comment by ashpath22** [comment]
thank you
