### ISSUE TITLE
Change the default path of created repositories.

### ISSUE THREAD

**Issue by Denis-Raev** [Ravinou/borgwarehouse#41]
Hello! Thanks for a cool product.

Please tell me. Where can I change the default path of created repositories in BorgWarehouse? Initially, it creates them along the /var/borgwarehouse path, but in my case, for example, this is a system partition and it is very limited in terms of memory and fault tolerance. I have a mounted disk on the /mnt partition that is much larger and has fault tolerance due to RAID5.

Thank you in advance for your response!

**Comment by Ravinou** [comment]
Hi, you can change the default path by using symbolic link. 

- FAQ : https://borgwarehouse.com/docs/help/faq/#can-i-change-the-directory-varborgwarehouse-

Thank you so much for your compliments, they give me the energy to keep going :)

**Comment by Denis-Raev** [comment]
@Ravinou Unfortunately the symlink won't let me take up space on the mounted drive, the symlink will still point to a directory in /var/borgwarehouse where space is severely limited by the system drives (240GB vs. mounted 12TB RAID 5 for backups). Perhaps I can change the path in the sources somewhere and then recompile the application?

**Comment by Denis-Raev** [comment]
I found where to replace the path in scripts. This is just what is needed.
![image](https://github.com/Ravinou/borgwarehouse/assets/23000390/6c46a30b-04ca-4812-8ab8-3180d07d8ca8)
