### ISSUE TITLE
Unable to initialize a directory from an ubuntu command line client

### ISSUE THREAD

**Issue by GabomaGeek** [Ravinou/borgwarehouse#44]
I tried to initialize a directory from a command line client but the problem is that the system asks for the password of the random user generated by borgwarehouse.
I don't understand how I can do.
I need your help.
Thanks in advance

**Comment by Ravinou** [comment]
Hi, I need more informations to help you.

- Do you copy the line that is generated with borgwarehouse ?
- You must have added an SSH public key to your repository. Are you connecting with the correct SSH private key?
- You can't SSH into the repository, BorgWarehouse has been designed to prevent this. Only borgbackup commands are allowed. [More info here](https://borgwarehouse.com/docs/user-manual/repositories/#ssh-public-key)

**Comment by GabomaGeek** [comment]
> Hi, I need more informations to help you.
> 
> * Do you copy the line that is generated with borgwarehouse ?
> * You must have added an SSH public key to your repository. Are you connecting with the correct SSH private key?
> * You can't SSH into the repository, BorgWarehouse has been designed to prevent this. Only borgbackup commands are allowed. [More info here](https://borgwarehouse.com/docs/user-manual/repositories/#ssh-public-key)

**Comment by GabomaGeek** [comment]
Yes, i copied the line but i was asked to put the password of the random user that was generated

**Comment by GabomaGeek** [comment]
`/var/borgwarehouse/<user>/.ssh/authorized_keys` does not exist on my server

**Comment by GabomaGeek** [comment]
> * Can you check the syslog when you connect to have more information please ?
> * Can you check your [sudoers file](https://github.com/Ravinou/borgwarehouse/blob/main/docs/sudoers/10-borgwarehouse), is it ok ?
> * Can you check the content in file `/var/borgwarehouse/<user>/.ssh/authorized_keys` please ?

I think I followed all the steps, but why this file does not exist on my server?

**Comment by Ravinou** [comment]
This file is created when you create a repository through borgwarehouse.

-------- Message d'origine --------

**Comment by GabomaGeek** [comment]
The directory `/var/borgwarehouse/` is empty
