### ISSUE TITLE
Cannot monitor the repos

### ISSUE THREAD

**Issue by GabomaGeek** [Ravinou/borgwarehouse#46]
I installed borgwarehouse on a VM and initialized a repository, but I can't monitor it. I can list the archives that are in the repository with `borg list ssh://user@vm_ip:22/./repo` but on borgwarehouse the dot is always red and I can't see the used storage space of the directory. 
Do you have any idea what could be causing this?
Thanks in advance.

**Comment by Ravinou** [comment]
These two functions come from cron. Have you set up the cron ?
- https://borgwarehouse.com/docs/admin-manual/debian-installation/#cron-jobs
 
If so, run the curl commands by hand and you can give me the result here.

**Comment by GabomaGeek** [comment]
Everything is working now. Thank you for your help
