### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by GabomaGeek** [Ravinou/borgwarehouse#48]
Hello.
My installed BorgWarehouse on a VM and everything was fine. But this morning i cannot acces it.
When i tried to restart the app i got this error `SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/home/borgwarehouse/borgwarehouse/.next/server/pages/api/cronjob/getStorageUsed.js:70:29)`.
I searched on the file and the line is that on `repoList = JSON.parse(repoList);
            //If repoList is empty we stop here.
            if (repoList.length === 0) {
                res.status(200).json({
                    success: "No repositories to analyse yet."
                });`
I"m not familiar with JS so i do not know why i have this error.
Thakns in advance for your help

**Comment by GabomaGeek** [comment]
The `/config/repo.json` file is empty

**Comment by Ravinou** [comment]
You need to rebuild the file. How many repository do you have please ?

You are the second person who have this problem, and I never experiment it or can find a way to recreate it.

You just need to rebuild with the help of this FAQ : https://borgwarehouse.com/docs/help/faq/#rebuild-the-repojson-file

The first issue about this problem is here : https://github.com/Ravinou/borgwarehouse/issues/34

Any informations about your installation, number of repository etc... can help me to find out this rare bug. Thanks.

**Comment by GabomaGeek** [comment]
I have 4 repositories. Borgwarehouse is installed on unbutu 22.04 VM

**Comment by GabomaGeek** [comment]
I executed your script and it seems like the app is running but some parts of the web interface are loaded.
Now i have  this other error `SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/home/borgwarehouse/borgwarehouse/.next/server/pages/api/repo.js:88:29)`

**Comment by Ravinou** [comment]
> This script should be used with the root user, as it is necessary to read authorized_keys files.
> 
> This script simply displays a valid JSON object on your screen. Copy its entire content into the config/repo.json file. There’s no need to restart or rebuild BorgWarehouse, as this can be done on the fly.

Did you copy the content display into config/repo.json after the execution of the script ?

**Comment by Ravinou** [comment]
@GabomaGeek I found the error that caused the `repo.json` file content to be deleted. It's fixed now and I recommend that you update BorgWarehouse to version 1.5.

You can [follow this documentation for the update](https://borgwarehouse.com/docs/admin-manual/how-to-update/).

All you have to do now is rebuild the file `repo.json` with the script.

**Comment by Ravinou** [comment]
In your message you have `No space left on device`, check your disk space usage please.

**Comment by Ravinou** [comment]
@GabomaGeek can I close this issue ?

**Comment by GabomaGeek** [comment]
Sorry for the late response. My installation work well, so you can close
the issue. Thank you very much for your time.
