### ISSUE TITLE
version listed as 1.0 (running 1.5)

### ISSUE THREAD

**Issue by hugalafutro** [Ravinou/borgwarehouse#49]
Hi, I just updated to 1.5, and afterwards when running `service borgwarehouse status` to confirm it's running ok I noticed it lists the version as 1.0'. Am I looking in wrong spot or where can I confim I updated correctly?
```
Aug 08 23:12:53 pi-docker npm[371652]: > borgwarehouse@1.0 start
```

Perhaps of note is then while updating when running `git pull` inside the `~/borgwarehouse` directory while logged as `borgwarehouse` user I was getting error 
```
borgwarehouse@pi-docker:~/borgwarehouse $ git pull
Updating d721377..182b282
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting
```
I moved the file out of the directory and could afterwards proceed. This is what was inside the file (you can see it says version 1.0 at the top): https://o.o5.ddns.net/h0qeO

The file got recreated during update, but inside it the versions are still listed as 1.0
```
{
    "name": "borgwarehouse",
    "version": "1.0",
    "lockfileVersion": 3,
    "requires": true,
    "packages": {
        "": {
            "name": "borgwarehouse",
            "version": "1.0",
```

I presume it's jsut an omission of updating the version number, but wanted to know a way be sure I am indeed running the latest version.

Thanks!

**Comment by Ravinou** [comment]
Sorry, it's fixed with [v1.5.1](https://github.com/Ravinou/borgwarehouse/releases/tag/v1.5.1)
