### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by dumbasPL** [Ravinou/borgwarehouse#57]
There is a lot that can be improved in that regard

- [ ] Maybe use a lighter base image. TODO: investigate if we can, because there is a bit more here than just nodejs
- [x] Build in a separate stage to avoid having the source code and unneeded dependencies in the final image (pretty sure we don't need the entire 220MB of node_modules)
- [x] Avoid chown since it effectively causes a copy of all the files affected

I'll try to make a PR later. 408MB for a web app and an SSH server is a bit much IMO.

**Comment by Ravinou** [comment]
Thank you very much for your help 🙏
