### ISSUE TITLE
How to uninstall when switching to docker?

### ISSUE THREAD

**Issue by hugalafutro** [Ravinou/borgwarehouse#59]
Hi, 
for now I just disabled the service, but is there a way to remove the bare-metal install of borgwarehouse after switching to docker deployment?

Thanks

**Comment by Ravinou** [comment]
Hey, sorry @hugalafutro , big week and no personal time for me this week ! I think you've done it all 👍

**Comment by hugalafutro** [comment]
@Ravinou don't worry about it I was just restless to try the docker deployment. In addition to the steps above I discovered I also had to remove the users created for each repo. I don't think they would cause issues, but it's in the spirit of 'leaving the host system unmodified'

**Comment by Ravinou** [comment]
Yes indeed, on Borgwarehouse v1, when you delete a repository, the associated unix user is also destroyed. But if you haven't deleted the repositories via the interface before uninstalling, you'll have to delete the users manually. Well, I'm glad you got away with it ;)
