### ISSUE TITLE
how to uninstall and remove the user and is the repos by user or are they all shared by on user

### ISSUE THREAD

**Issue by cchalifo999** [Ravinou/borgwarehouse#6]
how to uninstall and remove the user and is the repos by user or are they all shared by on user

**Comment by Ravinou** [comment]
Hey @cchalifo999 👋

Your answer is in the doc, just here : https://borgwarehouse.com/docs/user-manual/repositories/#delete-a-repository

One repository = one system user.
When you delete a repository on the BorgWarehouse interface, on the system side there will be :
- deletion of the system user
- deletion of all the repository data on the server (only for the one you delete)

This action is irreversible.

**Comment by cchalifo999** [comment]
> Hey @cchalifo999 wave
> 
> Your answer is in the doc, just here : https://borgwarehouse.com/docs/user-manual/repositories/#delete-a-repository
> 
> One repository = one system user. When you delete a repository on the BorgWarehouse interface, on the system side there will be :
> 
>     * deletion of the system user
> 
>     * deletion of all the repository data on the server (only for the one you delete)
> 
> 
> This action is irreversible.

ty i have brog server allready setup and i was going to install the web gui and i was not sure

**Comment by Ravinou** [comment]
The integration of existing repo is possible but you have to move your data manually into repositories created beforehand via the interface ( https://github.com/Ravinou/borgwarehouse/issues/4#issuecomment-1348900138 ).
