### ISSUE TITLE
Feature request: repo details

### ISSUE THREAD

**Issue by IntoTheWebNet** [Ravinou/borgwarehouse#63]
It would be good to get more details about the managed repositories from the web based dashboard.

Details like:
borg info
borg list --format '{archive:24}{TAB}{start}{TAB}{end}{NL}'

https://borgbackup.readthedocs.io/en/stable/usage/info.html
https://borgbackup.readthedocs.io/en/stable/usage/list.html

**Comment by Ravinou** [comment]
Hello, for the time being, BorgWarehouse plans to focus on **server functionality only**. End-to-end encryption does not allow access to this information without the transmission of the encryption password.

Borgwarehouse has also been created to enable backup on servers over which we have **no control**. Maybe one day I'll move towards these functionalities, but for the moment I think they belong to the BorgBackup **client** **first and foremost**, and BorgWarehouse is not a client.

I hope you'll understand, one day I'll integrate client functionalities into BorgWarehouse. But for the time being, BorgWarehouse is limited to the **server side** and therefore to any functionality that doesn't require a password, **so as not to interfere with the end-to-end's BorgBackup encryption design**.
