### ISSUE TITLE
Docker repos not showing any space used and as red dots

### ISSUE THREAD

**Issue by bigjdunham** [Ravinou/borgwarehouse#65]
I have been able to setup the Docker install of BorgWarehouse, and I can create repos and use borgmatic to setup my remotes to backup to the repos successfully. But the default page does not give me any data on the repos. It just shows a red dot next to each repo and still shows that 0% of the selected storage used. What could be happening? Any help would be great. Thanks.

**Comment by Ravinou** [comment]
Hi, if you are on a classical baremetal install, you just probably don't set the cronjob. Check this doc : https://borgwarehouse.com/docs/admin-manual/debian-installation/#cron-jobs

**Comment by Ravinou** [comment]
@bigjdunham your problem was certainly due to PR 58. It's fixed in the latest image, just update. More information here : https://github.com/Ravinou/borgwarehouse/issues/64

I close this issue.

**Comment by egoran2** [comment]
Hello, @Ravinou 
Just updated the image, but still se 0% of usage in docker compose version, how to check/debug this?

**Comment by egoran2** [comment]
Sorry, my bad, found in the documentation that cron is not included in the container now. Everything is ok :)
