### ISSUE TITLE
Automate Docker deployment with GitHub Actions

### ISSUE THREAD

**Issue by rugk** [Ravinou/borgwarehouse#67]
Both for security (fast releases, maybe even automatic when merged into the main branch, see https://github.com/Ravinou/borgwarehouse/pull/66) and convenience (see https://github.com/Ravinou/borgwarehouse/pull/58#issuecomment-1774077925) this would really be needed.

The web is full of references and if you still think you need help maybe ChatGPT can do so. Also https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/.github/workflows/build-images.yml is an example I can personally provide. (Though it has different image versions _and_ it also pushes to different container registries, so maybe a bit overblown.)

Though what I would recommend to integrate then is a OWASP security scan. Although wait this bit is easy to integrate as it exists already.

**Comment by Ravinou** [comment]
Hi, I'm trying to find time to consult the github action docs to automate these tasks. So thank you for your contributions :)

**Comment by rugk** [comment]
Yeah it's quite simple to do actually and GitHub has a web editor/website support for it. So yeah, if you have any questions, feel free to ask.

**Comment by Ravinou** [comment]
BorgWarehouse is now automatically deploy on DockerHub.

**Comment by rugk** [comment]
Awesome! BTW [maybe additionally deploying it in the GitHub Container registry](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/54165bb82e4e85896b40fa6121610e901b85979c/.github/workflows/build-images.yml#L38C7-L44C40) would be useful, as you then have a fallback for users and they can use the container from there too, e.g. if Dockerhub again tries to limit free accounts etc.

**Comment by Ravinou** [comment]
@rugk Do I need a specific account for deploy on github registry ? I will check this possibility. Thanks

**Comment by rugk** [comment]
No, as you can see in the link, you can just use your automatically added GitHub token. So just the usual GitHub account. That's why it is so simple to setup.
