### ISSUE TITLE
admin user unable to delete repos fresinstall

### ISSUE THREAD

**Issue by cchalifo999** [Ravinou/borgwarehouse#7]
admin user unable to delete repos fresinstall

**Comment by p-rintz** [comment]
What does the log for borgwarehouse say?

If you use systemd, you can get it with the following:
`sudo systemctl status borgwarehouse -n50`

**Comment by cchalifo999** [comment]
Dec 16 21:11:22 s403 sudo[5712]: pam_unix(sudo:session): session closed for user root
Dec 16 21:11:22 s403 sudo[5714]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=root ; COMMAND=/usr/bin/mkdir -p /var/borgwarehouse/48a97fb4/repos
Dec 16 21:11:22 s403 sudo[5714]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Dec 16 21:11:22 s403 sudo[5714]: pam_unix(sudo:session): session closed for user root
Dec 16 21:11:22 s403 sudo[5716]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=root ; COMMAND=/usr/bin/mkdir -p /var/borgwarehouse/48a97fb4/repos/repo0
Dec 16 21:11:22 s403 sudo[5716]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Dec 16 21:11:22 s403 sudo[5716]: pam_unix(sudo:session): session closed for user root
Dec 16 21:11:22 s403 sudo[5718]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=root ; COMMAND=/usr/bin/chmod -R 700 /var/borgwarehouse/48a97fb4
Dec 16 21:11:22 s403 sudo[5718]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Dec 16 21:11:22 s403 sudo[5718]: pam_unix(sudo:session): session closed for user root
Dec 16 21:11:22 s403 sudo[5720]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=root ; COMMAND=/usr/bin/chmod 600 /var/borgwarehouse/48a97fb4/.ssh/authorized_keys
Dec 16 21:11:22 s403 sudo[5720]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Dec 16 21:11:22 s403 sudo[5720]: pam_unix(sudo:session): session closed for user root
Dec 16 21:11:22 s403 sudo[5722]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=root ; COMMAND=/usr/bin/chown -R 48a97fb4:48a97fb4 /var/borgwarehouse/48a97fb4
Dec 16 21:11:22 s403 sudo[5722]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Dec 16 21:11:22 s403 sudo[5722]: pam_unix(sudo:session): session closed for user root
Dec 16 21:11:22 s403 sudo[5724]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=48a97fb4 ; COMMAND=/usr/bin/bash -c echo 'command="cd /var/borgwarehouse/48a97fb4/repos;borg ser>
Dec 16 21:11:22 s403 sudo[5724]: pam_unix(sudo:session): session opened for user 48a97fb4(uid=1005) by (uid=1001)
Dec 16 21:11:22 s403 sudo[5724]: pam_unix(sudo:session): session closed for user 48a97fb4
Dec 16 21:11:34 s403 sudo[5731]: borgwarehouse : PWD=/home/borgwarehouse/borgwarehouse ; USER=root ; COMMAND=/usr/bin/grep -q 48a97fb4 /etc/passwd
Dec 16 21:11:34 s403 sudo[5731]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Dec 16 21:11:34 s403 npm[5684]: Error: Command failed: /home/borgwarehouse/borgwarehouse/helpers/shells/deleteRepo.sh 48a97fb4
Dec 16 21:11:34 s403 npm[5684]: We trust you have received the usual lecture from the local System
Dec 16 21:11:34 s403 npm[5684]: Administrator. It usually boils down to these three things:
Dec 16 21:11:34 s403 npm[5684]:     #1) Respect the privacy of others.

**Comment by Ravinou** [comment]
Please, you have to detail your issues. If you want help you have to tell us what distribution you use, the context of installation, give us logs. 

On your previous issue you didn't read the documentation. If you are on debian did you follow the user installation documentation just here : https://borgwarehouse.com/docs/admin-manual/debian-installation/ ?

If the script doesn't run, you probably have a problem with script rights. What is the return of : 
```bash
ls -la /home/borgwarehouse/borgwarehouse/helpers/shells/
```

**Comment by cchalifo999** [comment]
> ```shell
> ls -la /home/borgwarehouse/borgwarehouse/helpers/shells/
> ```

drwxr-xr-x 2 borgwarehouse borgwarehouse 4096 Dec 16 21:05 .
drwxr-xr-x 4 borgwarehouse borgwarehouse 4096 Dec 16 21:05 ..
-rwx------ 1 borgwarehouse borgwarehouse 2959 Dec 16 21:05 createRepo.sh
-rwx------ 1 borgwarehouse borgwarehouse  796 Dec 16 21:05 deleteRepo.sh
-rwx------ 1 borgwarehouse borgwarehouse  558 Dec 16 21:05 getLastSave.sh
-rwx------ 1 borgwarehouse borgwarehouse  474 Dec 16 21:05 getStorageUsed.sh
-rwx------ 1 borgwarehouse borgwarehouse 1572 Dec 16 21:05 updateRepo.sh

**Comment by p-rintz** [comment]
Did you add the sudoers file under `/etc/sudoers.d/10-borgwarehouse` ?
Can you show what you've added?

In the log the application cannot run the script without being asked for a password from sudo. 
Specifically `/usr/bin/grep -q 48a97fb4 /etc/passwd` seems to fail.

**Comment by cchalifo999** [comment]
> Please, you have to detail your issues. If you want help you have to tell us what distribution you use, the context of installation, give us logs.
> 
> On your previous issue you didn't read the documentation. If you are on debian did you follow the user installation documentation just here : https://borgwarehouse.com/docs/admin-manual/debian-installation/ ?
> 
> If the script doesn't run, you probably have a problem with script rights. What is the return of :
> 
> ```shell
> ls -la /home/borgwarehouse/borgwarehouse/helpers/shells/
> `
It is working now , when i copy the Limitation of sudo commands available for borgwarehouse user : command i had a exter echo  in the file
