### ISSUE TITLE
NextAuth is deprecated? Rename environmental variables?

### ISSUE THREAD

**Issue by rugk** [Ravinou/borgwarehouse#70]
I see https://next-auth.js.org/ is deprecated and apparently now called [authjs.dev](https://authjs.dev/)?
In your env vars you still use `NEXTAUTH_URL` and `NEXTAUTH_SECRET`. Maybe rename/find some better name?

IMHO you can stay baackwards-compatible by falling back to the old env variable names if the new ones are not set. That should be possible, should not it?

Maybe take the chance to rename these in general to:
* `WEB_URL` 
* `AUTH_SECRET`

This would be independent of the implementation details _and_ would avoid confusion. Because at least I thought _NextAuth_ is some third-party auth portal, where I need to login/get an API key (secret) and paste it in there. Or somehow host it by myself (proving the URL). But if it is just the same URL of BorgWarehouse, well… then this is no problem.

**Comment by Ravinou** [comment]
Hey! Thanks for your contribution. Indeed, your comment is interesting, because when you take a step back it's true that it can look like a third-party brick. So the renaming (especially as nextauth is in the process of changing its name) is rather a good comment.

I'll look into implementing this without breaking the old variable naming.

**Comment by Ravinou** [comment]
After going back through the documentation of NextAuth and other configuration files, it's not really possible to change the name of this variable at the moment. It's not impossible to modify a conf file, but it's highly discouraged. The name of this variable is also hardcoded in the modules.

As for the change from NextAuth.js to Auth.js, this is still in experimental version.

So I'm going to keep things as they are, and I'll keep an eye on Auth.js in any case.
