### ISSUE TITLE
doc: Clarify it should not be run over HTTP

### ISSUE THREAD

**Issue by rugk** [Ravinou/borgwarehouse#71]
> For the NEXTAUTH_URL, be sure to specify the right protocol : http or https. Indicating an https URL when using http will make login impossible.

https://borgwarehouse.com/docs/admin-manual/env-vars/

This is fun, because obviously (at least when exposed  to the internet), the web interface should _never_ be run without HTTPS).

Maybe this could be worded better?
BTW I did not find the website doc (or this snippet) in this repo. I would have contributed otherwise directly. Where is the website source hmm?

**Comment by Ravinou** [comment]
Hi, it's recommended to use HTTPS but it's not impossible to use HTTP, so it's everyone's choice and I know that BorgWarehouse is used in LAN environments too, so I prefer to leave this choice as long as it's possible. 

Do you want me to add a warning to indicate that HTTPS should be used when the interface is on the Internet ? I can do that, but it's true that the documentation is aimed at administrators, so I didn't think to indicate that ^^.

The documentation isn't on a free repo at the moment, but it may be in the future.

**Comment by rugk** [comment]
> The documentation isn't on a free repo at the moment, but it may be in the future.

Maybe convert the project to an org and just push the doc? IMHO it helps immediately if people can contribute.

E.g. here is a typo that I could have fixed by myself in two seconds:
![grafik](https://github.com/Ravinou/borgwarehouse/assets/11966684/09cdcac7-2fe7-4699-9267-353ea55af81c)

on https://borgwarehouse.com/docs/admin-manual/env-vars/

**Comment by Ravinou** [comment]
Thank you, it's fixed.
