### ISSUE TITLE
aarch64 docker image architecture

### ISSUE THREAD

**Issue by UnixxSH** [Ravinou/borgwarehouse#86]
Hi !

Do you plan to add a aarch64 docker image of your app ?

The Docker support for 2.0.0 is a good thing, but as I'm hosting currently on a raspberry pi, I can't use the image.

Thank's for your work !

**Comment by Ravinou** [comment]
I just build the latest tag 2 days ago for arm, to test it for Rapsberry. It works well for me under rapsberry. Did you test with : `docker pull borgwarehouse/borgwarehouse:latest` ?

Let me know, because, I will release 2.0.1 soon and BorgWarehouse will be now always build for Rapsberry.

**Comment by UnixxSH** [comment]
Building with latest tag is working; I was using 2.0.0.

**Comment by Ravinou** [comment]
It's better to use a version tag than the latest tag. I'll do what's necessary to make the next version tag compatible with the ARM raspberry architecture. Thanks for your feedback, which confirms that it works :)

I close this issue
