### ISSUE TITLE
can't use same SSH public key for multiple repos

### ISSUE THREAD

**Issue by UnixxSH** [Ravinou/borgwarehouse#87]
I get this error when using the same SSH key for two repos:

![image](https://github.com/Ravinou/borgwarehouse/assets/17497055/cc5ba4fe-7dd9-4d20-b5ec-936d77c6244e)

This was working before 2.0. How could I use the same ?

**Comment by Ravinou** [comment]
You will find the answer in the documentation, [here](https://borgwarehouse.com/docs/admin-manual/how-to-update/#whats-new-in-v2-).

**Comment by UnixxSH** [comment]
Thank's for the clarification!
