### ISSUE TITLE
Docker Image for Raspberry Pi 4

### ISSUE THREAD

**Issue by nosbig** [Ravinou/borgwarehouse#91]
I love BorgBackup, and I would love to use this project for my at-home backup server.

I'm would like to use the Docker deployment over the bare-metal one, but my host is a Raspberry Pi 4 with some external USB drives attached.  When I attempt to launch docker-compose with the correct substitutions from the docker-compose.yml file, Docker complains that an image matching the CPU architecture doesn't match.

Are you only providing x86_64 images or is there an opportunity to have an arm image for the Pi family of systems?

**Comment by Ravinou** [comment]
Hi @nosbig , check this issue please : https://github.com/Ravinou/borgwarehouse/issues/86

Just pull the tag latest, it's build for Raspberry (ARM). All the future releases will be build for ARM but not the 2.0.0, use the "latest" tag for the moment.

Tell me if it's ok for you ?

Good night !

**Comment by nosbig** [comment]
I was able to pull manually via latest, and I was able to use docker-compose and Portainer to start the stack...  The issue was actually that the apprise container defined doesn't have an armv7 image associated with their latest tag.  I'm going to have to either use 0.9.2 or determine how to/use an external apprise server on another box.

I'm closing, as this isn't needed.

**Comment by dumbasPL** [comment]
I just noticed that `.github/workflows/docker-image-latest.yml` has `linux/amd64,linux/arm64,linux/arm` but `.github/workflows/docker-image-release.yml` and `.github/workflows/docker-image-test.yml` only have `linux/amd64,linux/arm64`

It would be nice to have a `linux/arm/v7` image available once the next tagged release drops. Also, I suggest replacing `linux/arm` with `linux/arm/v7`. They mean the same thing but the second one is more verbose. `linux/arm/v6` also exists but is quite rare nowadays.

**Comment by dumbasPL** [comment]
and now you removed arm64 in 7a205d66131682bdf57fca8f871803e9a49a9165 :facepalm: 

what I meant was to use: `platforms: linux/amd64,linux/arm64,linux/arm/v7`

This would build for `x86_64` (`amd64`), `aarch64` (`arm64`), and `armhf` (`arm/v7`)
Some devices (like the raspberry pi4) can run in either 32 or 64 bit based on the OS architecture installed so support for both is important IMO
